[package]
org = "david"
name = "transport"
version = "0.1.0"
distribution = "2201.12.9"

[build-options]
observabilityIncluded = true

[[dependency]]
org = "ballerina"
name = "time"
version = "2.7.0"

[[dependency]]
org = "ballerina"
name = "http"
version = "2.14.6"

[[dependency]]
org = "ballerina"
name = "log"
version = "2.13.0"

[[dependency]]
org = "ballerina"
name = "uuid"
version = "1.10.0"

[[dependency]]
org = "ballerina"
name = "regex"
version = "1.3.2"

[[dependency]]
org = "ballerinax"
name = "mongodb"
version = "5.2.2"

[[dependency]]
org = "ballerinax"
name = "kafka"
version = "4.6.1"